export const ENV = {
  PORT: process.env.PORT!,
  MONGO_URI: process.env.MONGO_URI!,
  NODE_ENV: process.env.NODE_ENV!,
  SALT_ROUND:process.env.SALT_ROUND!,
  ACCESS_TOKEN_SECRET:process.env.ACCESS_TOKEN_SECRET!,
  ACCESS_TOKEN_EXPIRY:process.env.ACCESS_TOKEN_EXPIRY as string,
  REFRESH_TOKEN_SECRET:process.env.REFRESH_TOKEN_SECRET!,
  REFRESH_TOKEN_EXPIRY:process.env.REFRESH_TOKEN_EXPIRY as string,
  FRONTEND_URL:process.env.FRONTEND_URL!,
  ADMIN_FRONTEND_URL:process.env. ADMIN_FRONTEND_URL!,
  CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET!,
  CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY!,
  CLOUDINARY_NAME:process.env.CLOUDINARY_NAME!,
  GEMINI_API_KEY:process.env.GEMINI_API_KEY!
};